# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Tensile', kernelModule='abaqusMacros', kernelFunction='Tensile_model', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgVerticalFrame(name='VFrame_1', p='DialogBox', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Assign')
RsgHorizontalFrame(name='HFrame_1', p='TabItem_1', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgComboBox(name='ComboBox_5', p='HFrame_1', text='Metal:', keyword='Metal_text', default='', comboType='STANDARD', repository='', rootText='', rootKeyword='None', layout='')
materials = mdb.models['Model-1'].materials.keys()
for material in materials:
    RsgListItem(p='ComboBox_5', text=material)
RsgComboBox(name='ComboBox_4', p='HFrame_1', text='FRP:', keyword='FRP_text', default='', comboType='STANDARD', repository='', rootText='', rootKeyword='None', layout='')
for material in materials:
    RsgListItem(p='ComboBox_4', text=material)
RsgTextField(p='HFrame_1', fieldType='String', ncols=12, labelText='Part name:', keyword='k1', default='')
RsgTable(p='TabItem_1', numRows=7, columnData=[('Metal', 'Bool', 100), ('FRP', 'Bool', 100), ('Thickness(mm)', 'Float', 100), ('Rotation Angle(FRP only)', 'Float', 100)], showRowNumbers=True, showGrids=True, keyword='table_val', popupFlags='AFXTable.POPUP_INSERT_ROW')
RsgSeparator(p='TabItem_1')
RsgLabel(p='TabItem_1', text='A layer can only choose one material, choose two or zero will not be included in the program.', useBoldFont=True)
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Tab')
dialogBox.show()